name: Keep V2Ray Alive

on:
  schedule:
    - cron: "10 */5 * * *"  # 每 5 小时 + 10 分钟 触发一次
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ssh-forward workflow
        uses: peter-evans/workflow-dispatch@v2
        with:
          workflow: "ssh-forward.yaml"
          ref: "main"
